### ISSUE TITLE
report: PPP – descriptive text - DONE

### ISSUE THREAD

**Issue by silverbytes** [silverbytes/identiPhytes#17]
@Chris: Visual design principles; User Interface; elaborate on structural design choices in harmony with conclusion & problem statement – Ich brauche einen kurzen Text (ca. 250 Wörter) zu deinen Designentscheidungen im Rahmen des Power Point Prototypes.

**Comment by niddhog** [comment]
currently working on this. Will upload my 250 Word document today (bevor 20:00) onto Switchdrive. Will update this issue once finished

**Comment by niddhog** [comment]
Description added to Switchdrive --> Prototypes --> Initial Prototype description Chris.docx

**Comment by silverbytes** [comment]
Top, danke!
