### ISSUE TITLE
Create Midterm Report

### ISSUE THREAD

**Issue by silverbytes** [silverbytes/identiPhytes#2]
- [x] : Intro describing the problem and how we plan to address it
- [x] : short block covering Interview & exploration
- [x] : include storyboard showing status quo @niddhog 
- [x] : Related Work (2-3 similar products (Apps), related academic research from HCI. Describe how our approach differs.
- [x] : output self-contained, as PDF

- [ ] : Examples for Intro and Related Work: 
[Michalsky et al. (CHI EA ’18)](https://doi.org/10.1145/3170427.3180655)
[Andrich et al. (CHI EA ’18)](https://doi.org/10.1145/3170427.3180645)

**Comment by niddhog** [comment]
If we want we can include a Story Board (Status Quo) about how what the User currently uses (Invasive App, Pl@ntnet App) and how he uses this. I'll be taking care of this Task

**Comment by silverbytes** [comment]
@KarimAbouelNaga @dombosfi Jungs, dTasklist obe isch natürli nu en Vorschlag!  Go wild!! *markdown* :-)

**Comment by niddhog** [comment]
Storyboard has been included in the Midterm report found on Switchdrive. Please proof-read by chance

**Comment by silverbytes** [comment]
> Storyboard has been included in the Midterm report found on Switchdrive. Please proof-read by chance

Ist ein Storyboard normalerweise nicht, ähh, ein Storyboard? :) Also so als Situationszeichnung? Und in unserem Fall wäre das eher auf einen möglichen Prototypen zu beziehen? Oder interpretiere ich das falsch?

**Comment by silverbytes** [comment]
@KarimAbouelNaga @dombosfi Bezüglich «related Work»: Ich denke, hier geht es uns sinnvollerweise vor allem um eine kurze Analyse der schon bekannten Apps hinsichtlich Funktionalität und Usability, oder? Wie seht ihr das?

Das könnte man dann kurz kontrastieren mit einigen ersten «key findings» unserer Exploration («describe how our approach differs»).

Deshalb wäre es ganz gut, euch zwei diesbezüglich noch auf den aktuellen Stand zu bringen (morgen hoffen wir Affinity noch abzuschliessen) – wir könnten euch ein paar dieser «key findings»  runterschreiben – oder wir könnten versuchen, uns am WE nochmals zu treffen. TBD!

**Comment by niddhog** [comment]
@silverbyte ja du hast recht, habe das völlig falsch verstanden...ich schaue mal was ich diesbezüglich machen kann. Halte euch hier auf dem laufenden
@KarimAbouelNaga @dombosfi Analysiert doch am besten das InvasivApp und Pl@ntnet App, diese beiden Apps wurden bei uns im Interview mit den Interviewpartnern getestet. Wichtige Punkte dabei sind: Wie kann man mittels InvasivApp als Projektgruppe arbeiten (Gibt es Projektfolders (ja, gibt es), und welche Funktionalitäten lassen sich mit diesen Projektfoldern verwirklichen), wie verläuft der Datenerfassungsprozess (Eingabemaske analysieren, idealerweise mit Bezug zur Gestalt Theory (Affordance, Signifiers etc.), welche Hilfestellung Bieten die Apps hinsichtlich Neophytenbestimmung etc. 
Auf unseren Interview Audio Files und Transkripten könnt ihr nachlesen, was alles mit dem Einsatzleiter und Zivi getestet wurde. Wichtig ist, dass ihr die Apps nicht einfach zufällig beschreibt, sondern mit Augenmerk auf die "Traits", die für unsere weiterführende Arbeit relevant sind.

**Comment by silverbytes** [comment]
>  idealerweise mit Bezug zur Gestalt Theory (Affordance, Signifiers)
Finde, das ist ein guter Hinweis! Man muss es ja nicht übertreiben, aber das ist genau etwas, was sicher positiv vermerkt werden wird.
